// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaKA9m4oMsKk-K9-3-PjtlRItPH9RR_Xg',
    appId: '1:1059925078848:web:bd946af60e58067f6e80a5',
    messagingSenderId: '1059925078848',
    projectId: 'wise-wigie',
    authDomain: 'wise-wigie.firebaseapp.com',
    storageBucket: 'wise-wigie.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0KnRazI-q6dyAhypk1yEVSixeyCacl70',
    appId: '1:1059925078848:android:85b7698ee8680f096e80a5',
    messagingSenderId: '1059925078848',
    projectId: 'wise-wigie',
    storageBucket: 'wise-wigie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0fN8YCsJSolPTJgIbizFh8Jn5l5lHA0U',
    appId: '1:1059925078848:ios:49824f993ef5060d6e80a5',
    messagingSenderId: '1059925078848',
    projectId: 'wise-wigie',
    storageBucket: 'wise-wigie.firebasestorage.app',
    iosBundleId: 'com.example.tester',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0fN8YCsJSolPTJgIbizFh8Jn5l5lHA0U',
    appId: '1:1059925078848:ios:49824f993ef5060d6e80a5',
    messagingSenderId: '1059925078848',
    projectId: 'wise-wigie',
    storageBucket: 'wise-wigie.firebasestorage.app',
    iosBundleId: 'com.example.tester',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaKA9m4oMsKk-K9-3-PjtlRItPH9RR_Xg',
    appId: '1:1059925078848:web:8dd643e8de3e0d586e80a5',
    messagingSenderId: '1059925078848',
    projectId: 'wise-wigie',
    authDomain: 'wise-wigie.firebaseapp.com',
    storageBucket: 'wise-wigie.firebasestorage.app',
  );
}
